### ISSUE TITLE
feat: frontend environment

### ISSUE THREAD

**Issue by KeidsID** [KeidsID/task-sync#8]
### What feature?

There's still no frontend environment defined on the project repository.

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added frontend workspace to package.json, created a new package.json for the frontend, and updated README.md with frontend information.

You can review changes in this commit: https://github.com/lkilu6456546/KeidsID-task-sync-8/commit/e1b5dd31899739c4b41e10d8579c2d79333b5f9e.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
